services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=TB&0*ybP*3u3P0
      - POSTGRES_DB=feub_bacasable
      - POSTGRES_USER=feub
      - POSTGRES_HOST=postgresql-feub.alwaysdata.net
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        npm run seed
        npm run test
    restart: always
    environment:
      - POSTGRES_PASSWORD=TB&0*ybP*3u3P0
      - POSTGRES_DB=feub_bacasable
      - POSTGRES_USER=feub
      - POSTGRES_HOST=postgresql-feub.alwaysdata.net
    depends_on:
      db:
        condition: service_healthy
